### ISSUE TITLE
I have more than one zone ID for an app.

### ISSUE THREAD

**Issue by SoloCarryGuy** [DrMoriarty/godot-adcolony#1]
I have two zone ID's for an app one for interstitial and one for rewarded but the plug in is giving me only one input option for zone ID. How do I set it up if I have more than one zone id?

**Comment by DrMoriarty** [comment]
You can set several zoneIds separated by comma.

**Comment by SoloCarryGuy** [comment]
That worked but now, when I try to run in mobile it gives me this error. 
```
01-21 00:42:26.685 14456 14456 E godot   : RN: No intent in app activity!
01-21 00:42:26.853 14456 14456 E godot   : RN: No extra bundle in app activity!
01-21 00:44:43.398 14687 14687 E godot   : RN: No intent in app activity!
01-21 00:44:43.567 14687 14687 E godot   : RN: No extra bundle in app activity!
```

**Comment by DrMoriarty** [comment]
This is debug output from another plugin. From localnotification as far as I remember. Just don't mind of it.

**Comment by SoloCarryGuy** [comment]
But, the game does not run. It crashes on startup. Same happens with applovin plugin.

**Comment by DrMoriarty** [comment]
what Godot version do you use?

**Comment by SoloCarryGuy** [comment]
3.2.2

**Comment by SoloCarryGuy** [comment]
The other stuff from your repositories work. I have local notifications, firebase analytics and rate me plugins.

**Comment by DrMoriarty** [comment]
I'm not sure that plugin works with this version. I tested only with 3.2.3-stable and 3.2.4-beta.
Now (several minutes ago) I updated adcolony for latest 3.2.4-beta. 
To install new version of plugin you should update repo information (right bottom button REPO)

**Comment by DrMoriarty** [comment]
tomorrow I will update applovin for latest SDK and for godot 3.2.4-beta

**Comment by SoloCarryGuy** [comment]
Okay. I will update my version of godot and open another issue if I cannot get it to work.
