### ISSUE TITLE
Issue with plug-in in godot v3.2.3 stable.

### ISSUE THREAD

**Issue by SoloCarryGuy** [DrMoriarty/godot-adcolony#2]
Hello, I still have the same issue after updating Godot to v3.2.3 stable. 
The error message I get when I export it to android -
```
01-21 12:11:33.177 15983 15983 E Godot   : RN: No intent in app activity!
01-21 12:11:33.597 15983 15983 E Godot   : RN: No extra bundle in app activity!
```
This happens in both adcolony and applovin
Rate me, local notification, Firebase analytics plugins work.

**Comment by DrMoriarty** [comment]
@SoloCarryGuy 
Are your app crashed or not?

**Comment by SoloCarryGuy** [comment]
Yes. It crashes on startup.

**Comment by DrMoriarty** [comment]
Give me full log, please.

**Comment by SoloCarryGuy** [comment]
First one is when I try to open the game, second one is the whole installation process.

[openAttemptLogcat.txt](https://github.com/DrMoriarty/godot-adcolony/files/5847928/openAttemptLogcat.txt)
[installationlogcat.txt](https://github.com/DrMoriarty/godot-adcolony/files/5847929/installationlogcat.txt)

**Comment by DrMoriarty** [comment]
It seems that problem in applovin plugin. Try to update it to version 0.2.0 (released today).

**Comment by SoloCarryGuy** [comment]
AdColony and AppLovin plugins work now. Thank you. Closing the issue.
