### ISSUE TITLE
I can't make the ads appear

### ISSUE THREAD

**Issue by betotulkas** [DrMoriarty/godot-adcolony#4]
[image1](https://mega.nz/file/a9xH0IrK#1KwOhS6UKYXNap0LkD7-29zR-PtIvRfXHL-rSplhFMk) hi.I think I have everything in order but I can't make the ads appear yet, now if the plugin appears in the export tab but it does not show anything although it can be played well, in the same way I tried to install the tadaq plugin then with adcolony and I skip an error alert, the images show how it is in the project. [`image2`](https://mega.nz/file/m1BnmCzQ#PmBbCToNOOdeG10dxd_RL8-x9NjMvGShZqkn1tFC8iE) This is the image from before how I had put the app id and zone id, the plugin is already corrected in the export tab sorry for the inconvenience

**Comment by DrMoriarty** [comment]
Hi!
It is not recommended to use ad SDK and the same SDK adapter for another network in the same time (in your case AdColony and Tapdaq-AdColony). It may lead to some internal conflicts or crashes.
If you can not show ads check that you call `showBanner` after the callback `_on_banner_loaded` and check if you use the same ZoneID for it.
Also you can get application logs and put it to new gist (https://gist.github.com) it will be useful for debugging.

**Comment by DrMoriarty** [comment]
Also if your ad network don't work in test mode it may not provide ad content and the application can not show anything.
By the way, it will be shown in application logs.

**Comment by betotulkas** [comment]
They have already appeared, what I did was reinstall the entire android studio and redefine the paths in the editor tab of godot, the version that I used of godot was 3.2.4 beta 4. Thanks man

**Comment by DrMoriarty** [comment]
Great!
