### ISSUE TITLE
AdColony Module not found

### ISSUE THREAD

**Issue by CrypticDevYT** [DrMoriarty/godot-adcolony#5]
hey, i just started using nativelib to install adcolony but i keep getting this warning "call: adcolony module not found" any help is appreciate thanks

**Comment by DrMoriarty** [comment]
Hello!
Check if you enabled platforms for your project before installing plugin. There are platforms checkboxes in the top of NativeLib addon view.
Then check if you enabled plugin in the export window (for Android).

**Comment by CrypticDevYT** [comment]
i tried doing what you said but it still saying the warning. This is the code that give the error.

func _ready():
	pause_mode = Node.PAUSE_MODE_PROCESS
	if(Engine.has_singleton("AdColony")):
		_ads = Engine.get_singleton("AdColony")
	else:
		push_warning('AdColony module not found!')
	if ProjectSettings.has_setting('AdColony/AppId'):
		var appId = ProjectSettings.get_setting('AdColony/AppId')
		var zoneId = ProjectSettings.get_setting('AdColony/ZoneId')
		init(appId, zoneId)

**Comment by DrMoriarty** [comment]
send me your exported APK file. I will check it.

**Comment by CrypticDevYT** [comment]
https://drive.google.com/file/d/1u2qOMrmQenZtlVrSUeHm9o1GtjDDWxzX/view?usp=sharing

**Comment by DrMoriarty** [comment]
In your apk I see that AdColony initialized successfully:
```
    GodotPluginRegistry  I  Initializing Godot plugin AdColony
                         I  Completed initialization for Godot plugin AdColony
```
and
```
        AdColony [INFO]  I  Configuring AdColony
     AdColony [WARNING]  W  Google Play Services ads dependencies are missing. Collecting Android ID instead of Advertising ID.
```
Also I don't see warning 'AdColony module not found!'

**Comment by CrypticDevYT** [comment]
its in the engine the error comes from the adcolony script

**Comment by DrMoriarty** [comment]
Ok. If you are running the game in godot's simulator there will this warning because AdColony library don't work in simulator.
If you run the game on android device it should not show this warning because AdColony library sucessfully loaded and inited (as I saw in logs of your APK).
Describe with more details If you think that you have an issue.

**Comment by CrypticDevYT** [comment]
Ok thank you for the help
