### ISSUE TITLE
GDPR requirements 

### ISSUE THREAD

**Issue by CrypticDevYT** [DrMoriarty/godot-adcolony#6]
hey, its me again i got ads to work and i used the test ad and it said i needed consent parameters how would i do that? Also it said that i didnt have the latest sdk version. thanks in advance

![app LoveCalc CheeseGames_Screenshot_2021 03 08_16 24 08](https://user-images.githubusercontent.com/69996409/110395100-cc547180-802a-11eb-83bf-53a28f248fd1.jpeg)

**Comment by CrypticDevYT** [comment]
the sdk version warning is gone now

**Comment by DrMoriarty** [comment]
Hello! For GDPR you can use https://ogury.com or https://fundingchoices.google.com/
There are plugin for ogury https://github.com/DrMoriarty/godot-ogury

**Comment by CrypticDevYT** [comment]
Ok thank you also sometimes when I try to use ads it give me the error "interstitial not found: my zone id"

**Comment by DrMoriarty** [comment]
check if you provided add zone ids in plugin settings
![Снимок экрана 2021-03-09 в 08 53 58](https://user-images.githubusercontent.com/1177068/110425214-08341900-80b5-11eb-9b71-a3d258dded64.png)

**Comment by CrypticDevYT** [comment]
I did, sometimes when I export this happens and sometimes it doesn't

**Comment by DrMoriarty** [comment]
may be it is a warning from your network which tells you that there are no available content for you?

**Comment by CrypticDevYT** [comment]
Not sure but it is working now. also is there a way to update the sdk?

**Comment by DrMoriarty** [comment]
I updated plugin to version 0.2.1 with latest adcolony SDK

**Comment by CrypticDevYT** [comment]
Ok thank you very much for the help 😊

**Comment by DrMoriarty** [comment]
:-) feel free to buy me a coffee https://ko-fi.com/drmoriarty
