### ISSUE TITLE
App freezing when trying to load interstial

### ISSUE THREAD

**Issue by jkelepolo** [DrMoriarty/godot-adcolony#7]
When I try to show an interstitial ad on my phone the app just freezes indefinitely

Code:
func _ready():
	adcolony.loadInterstitial("ZoneID", 0)
	adcolony.showInterstitial("ZoneID")

I also don't know how to access the callback functions for example:
_on_interstitial_loaded("ZoneID"):
         adcolony.showInterstitial("ZoneID")

This is my last hope for ads as admob has no reachable customer support...

**Comment by DrMoriarty** [comment]
you should do that:
```
func _ready():
  adcolony.loadInterstitial("zone id", get_instance_id())

func _on_interstitial_loaded(id: String) -> void:
  adcolony.showInterstitial(id)

func _on_interstitial_failed_to_load(id: String, error: String) -> void:
  print("Interstitial failed with id: %s, error: %s"%[id, error])
```

**Comment by DrMoriarty** [comment]
two words about admob. In my own projects I use AdMob with mediation layer: TapDaq or Applovin-Max. Plugins for both of them available in NativeLib. I think that it is enough for regular mobile game.

**Comment by jkelepolo** [comment]
> two words about admob. In my own projects I use AdMob with mediation layer: TapDaq or Applovin-Max. Plugins for both of them available in NativeLib. I think that it is enough for regular mobile game.

My issue is that I can't even create an account.. it thinks I already have one but I do not. admob linked an email that is not even mine to me saying that I already have a admob account and disables any attempts at creating a new one...

Still no luck getting an interstitial to show up :/

So I tried this out:

func _ready():
	print(adcolony.loadInterstitial("zone id", get_instance_id()))

and it was returning false.. then randomly started giving me this error:
Invalid call. Nonexistent function 'loadInterstitial' in base 'Nil'.

it fixes when I re-install the plugin but eventually starts giving me the error again...

**Comment by DrMoriarty** [comment]
if you have `Nonexistent function 'loadInterstitial' in base 'Nil'` than there are issue with the plugin initialization. Check if it is in your autoloading list, check if it installed for your platform (it shows installed platforms by green symbols in NativeLib view)

**Comment by jkelepolo** [comment]
![image](https://user-images.githubusercontent.com/80716026/122651970-fa008a80-d0f0-11eb-87be-94070392e78e.png)
![image](https://user-images.githubusercontent.com/80716026/122651983-18668600-d0f1-11eb-9be7-36f0eb6dc243.png)

Not sure what is wrong.. everything seems to be in place

**Comment by DrMoriarty** [comment]
can you show me raw logcat output of your game?

**Comment by jkelepolo** [comment]
> can you show me raw logcat output of your game?

How do I do this?

![image](https://user-images.githubusercontent.com/80716026/122652238-9a0ae380-d0f2-11eb-927c-7dd415c415ea.png)
also it appears the singleton just isn't loading for some reason

**Comment by DrMoriarty** [comment]
Are there any errors in file adcolony.gd if you open it in godot editor?

**Comment by jkelepolo** [comment]
No

**Comment by jkelepolo** [comment]
Is there a pathing issue maybe? because it looks like it is trying to create the singleton in a "scripts" folder when I already have a "Scripts" folder

**Comment by DrMoriarty** [comment]
Are you sure that this file exists in your export APK?

**Comment by DrMoriarty** [comment]
> Is there a pathing issue maybe? because it looks like it is trying to create the singleton in a "scripts" folder when I already have a "Scripts" folder

It is very bad case. Two folders with only one difference in case of a symbol should export with errors. It is the rule.

**Comment by jkelepolo** [comment]
> Are you sure that this file exists in your export APK?

How can I check this? I also renamed my personal scripts folder to game_scripts and am still getting the singleton doesn't exist error

**Comment by jkelepolo** [comment]
The warning is coming from these lines
func _ready():
	pause_mode = Node.PAUSE_MODE_PROCESS
	if(Engine.has_singleton("AdColony")):
		_ads = Engine.get_singleton("AdColony")
	else:
		push_warning('AdColony module not found!')
	if ProjectSettings.has_setting('AdColony/AppId'):
		var appId = ProjectSettings.get_setting('AdColony/AppId')
		var zoneId = ProjectSettings.get_setting('AdColony/ZoneId')
		init(appId, zoneId)

**Comment by DrMoriarty** [comment]
Are you enabled the plugin in your export settings?

**Comment by jkelepolo** [comment]
> Are you enabled the plugin in your export settings?

oops.. this is my first time trying to export to android using godot.. didn't realize I had to do that.

When trying to set up a custom build I am getting these errors
![image](https://user-images.githubusercontent.com/80716026/122653200-fae8ea80-d0f7-11eb-8b59-5bc3adaeaa61.png)

**Comment by DrMoriarty** [comment]
I think that I can not help with this issue. Refer to godot export template building documentation.

**Comment by jkelepolo** [comment]
> I think that I can not help with this issue. Refer to godot export template building documentation.

Okay thanks! I think you might have helped solve the other issue!
